package sevenno_addons.common.block.generation;

import java.util.Random;

import sevenno_addons.common.block.SABlockList;
import net.minecraft.block.Block;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;

public class GiantGreenMushroomGeneration extends WorldGenerator
{
    public GiantGreenMushroomGeneration(boolean dogen)
    {
        super(dogen);
    }
	public boolean generate(World world, Random rand, int x, int y, int z)
	{
		world.setBlock(x - 10, y + 17, z - 3, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 10, y + 17, z - 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 17, z - 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 17, z + 0, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 17, z + 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 17, z + 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 17, z + 3, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 10, y + 18, z - 3, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 10, y + 18, z - 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 18, z - 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 18, z + 0, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 18, z + 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 18, z + 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 18, z + 3, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 10, y + 19, z - 3, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 10, y + 19, z - 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 19, z - 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 19, z + 0, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 19, z + 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 19, z + 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 19, z + 3, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 10, y + 20, z - 3, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 10, y + 20, z - 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 20, z - 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 20, z + 0, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 20, z + 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 20, z + 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 20, z + 3, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 10, y + 21, z - 3, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 10, y + 21, z - 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 21, z - 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 21, z + 0, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 21, z + 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 21, z + 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 21, z + 3, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 10, y + 22, z - 3, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 10, y + 22, z - 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 22, z - 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 22, z + 0, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 22, z + 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 22, z + 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 22, z + 3, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 10, y + 23, z - 2, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 10, y + 23, z - 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 23, z + 0, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 23, z + 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 23, z + 2, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 10, y + 24, z - 1, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 10, y + 24, z + 0, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 10, y + 24, z + 1, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 9, y + 17, z - 5, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 9, y + 17, z - 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 17, z + 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 17, z + 5, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 9, y + 18, z - 5, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 9, y + 18, z - 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 18, z + 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 18, z + 5, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 9, y + 19, z - 5, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 9, y + 19, z - 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 19, z + 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 19, z + 5, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 9, y + 20, z - 5, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 9, y + 20, z - 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 20, z + 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 20, z + 5, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 9, y + 21, z - 5, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 9, y + 21, z - 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 21, z + 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 21, z + 5, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 9, y + 22, z - 5, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 9, y + 22, z - 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 22, z + 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 22, z + 5, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 9, y + 23, z - 5, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 9, y + 23, z - 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 23, z - 3, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 23, z + 3, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 23, z + 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 23, z + 5, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 9, y + 24, z - 4, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 9, y + 24, z - 3, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 24, z - 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 24, z + 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 24, z + 3, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 24, z + 4, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 9, y + 25, z - 3, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 9, y + 25, z - 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 25, z - 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 25, z + 0, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 25, z + 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 25, z + 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 25, z + 3, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 9, y + 26, z - 2, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 9, y + 26, z - 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 26, z + 0, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 26, z + 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 9, y + 26, z + 2, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 8, y + 17, z - 6, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 8, y + 17, z + 6, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 8, y + 18, z - 6, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 8, y + 18, z + 6, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 8, y + 19, z - 6, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 8, y + 19, z + 6, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 8, y + 20, z - 6, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 8, y + 20, z + 6, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 8, y + 21, z - 6, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 8, y + 21, z + 6, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 8, y + 22, z - 6, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 8, y + 22, z + 6, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 8, y + 23, z - 6, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 8, y + 23, z + 6, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 8, y + 24, z - 6, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 8, y + 24, z - 5, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 8, y + 24, z + 5, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 8, y + 24, z + 6, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 8, y + 25, z - 5, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 8, y + 25, z - 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 8, y + 25, z + 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 8, y + 25, z + 5, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 8, y + 26, z - 4, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 8, y + 26, z - 3, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 8, y + 26, z + 3, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 8, y + 26, z + 4, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 8, y + 27, z - 3, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 8, y + 27, z - 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 8, y + 27, z - 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 8, y + 27, z + 0, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 8, y + 27, z + 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 8, y + 27, z + 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 8, y + 27, z + 3, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 7, y + 17, z - 7, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 7, y + 17, z + 7, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 7, y + 18, z - 7, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 7, y + 18, z + 7, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 7, y + 19, z - 7, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 7, y + 19, z + 7, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 7, y + 20, z - 7, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 7, y + 20, z + 7, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 7, y + 21, z - 7, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 7, y + 21, z + 7, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 7, y + 22, z - 7, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 7, y + 22, z + 7, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 7, y + 23, z - 7, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 7, y + 23, z + 7, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 7, y + 24, z - 7, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 7, y + 24, z + 7, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 7, y + 25, z - 6, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 7, y + 25, z + 6, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 7, y + 26, z - 6, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 7, y + 26, z - 5, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 7, y + 26, z + 5, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 7, y + 26, z + 6, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 7, y + 27, z - 5, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 7, y + 27, z - 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 7, y + 27, z + 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 7, y + 27, z + 5, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 7, y + 28, z - 3, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 7, y + 28, z - 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 7, y + 28, z - 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 7, y + 28, z + 0, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 7, y + 28, z + 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 7, y + 28, z + 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 7, y + 28, z + 3, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 6, y + 17, z - 8, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 6, y + 17, z + 8, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 6, y + 18, z - 8, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 6, y + 18, z + 8, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 6, y + 19, z - 8, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 6, y + 19, z + 8, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 6, y + 20, z - 8, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 6, y + 20, z + 8, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 6, y + 21, z - 8, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 6, y + 21, z + 8, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 6, y + 22, z - 8, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 6, y + 22, z + 8, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 6, y + 23, z - 8, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 6, y + 23, z + 8, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 6, y + 24, z - 8, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 6, y + 24, z + 8, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 6, y + 25, z - 7, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 6, y + 25, z + 7, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 6, y + 26, z - 7, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 6, y + 26, z + 7, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 6, y + 27, z - 6, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 6, y + 27, z + 6, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 6, y + 28, z - 5, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 6, y + 28, z - 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 6, y + 28, z + 4, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 6, y + 28, z + 5, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 6, y + 29, z - 3, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 6, y + 29, z - 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 6, y + 29, z - 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 6, y + 29, z + 0, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 6, y + 29, z + 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 6, y + 29, z + 2, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 6, y + 29, z + 3, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 5, y + 17, z - 9, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 5, y + 17, z + 9, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 5, y + 18, z - 9, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 5, y + 18, z + 9, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 5, y + 19, z - 9, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 5, y + 19, z + 9, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 5, y + 20, z - 9, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 5, y + 20, z + 9, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 5, y + 21, z - 9, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 5, y + 21, z + 9, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 5, y + 22, z - 9, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 5, y + 22, z + 9, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 5, y + 23, z - 9, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 5, y + 23, z + 9, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 5, y + 24, z - 8, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 5, y + 24, z + 8, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 5, y + 25, z - 8, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 5, y + 25, z + 8, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 5, y + 26, z - 7, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 5, y + 26, z + 7, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 5, y + 27, z - 7, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 5, y + 27, z + 7, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 5, y + 28, z - 6, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 5, y + 28, z - 5, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 5, y + 28, z + 5, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 5, y + 28, z + 6, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 5, y + 29, z - 4, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 5, y + 29, z - 3, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 5, y + 29, z + 3, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 5, y + 29, z + 4, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 5, y + 30, z - 2, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 5, y + 30, z - 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 5, y + 30, z + 0, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 5, y + 30, z + 1, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 5, y + 30, z + 2, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 4, y + 17, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 4, y + 17, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 4, y + 18, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 4, y + 18, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 4, y + 19, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 4, y + 19, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 4, y + 20, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 4, y + 20, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 4, y + 21, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 4, y + 21, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 4, y + 22, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 4, y + 22, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 4, y + 23, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 4, y + 23, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 4, y + 24, z - 9, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 4, y + 24, z + 9, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 4, y + 25, z - 8, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 4, y + 25, z + 8, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 4, y + 26, z - 8, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 4, y + 26, z + 8, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 4, y + 27, z - 7, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 4, y + 27, z + 7, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 4, y + 28, z - 6, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 4, y + 28, z + 6, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 4, y + 29, z - 5, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 4, y + 29, z - 4, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 4, y + 29, z + 4, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 4, y + 29, z + 5, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 4, y + 30, z - 3, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 4, y + 30, z - 2, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 4, y + 30, z - 1, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 4, y + 30, z + 0, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 4, y + 30, z + 1, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 4, y + 30, z + 2, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 4, y + 30, z + 3, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 3, y + 17, z - 10, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 3, y + 17, z + 10, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 3, y + 18, z - 10, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 3, y + 18, z + 10, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 3, y + 19, z - 10, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 3, y + 19, z + 10, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 3, y + 20, z - 10, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 3, y + 20, z + 10, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 3, y + 21, z - 10, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 3, y + 21, z + 10, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 3, y + 22, z - 10, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 3, y + 22, z + 10, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 3, y + 23, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 3, y + 23, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 3, y + 24, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 3, y + 24, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 3, y + 25, z - 9, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 3, y + 25, z + 9, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 3, y + 26, z - 8, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 3, y + 26, z + 8, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 3, y + 27, z - 8, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 3, y + 27, z + 8, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 3, y + 28, z - 7, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 3, y + 28, z + 7, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 3, y + 29, z - 6, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 3, y + 29, z - 5, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 3, y + 29, z + 5, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 3, y + 29, z + 6, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 3, y + 30, z - 4, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 3, y + 30, z - 3, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 3, y + 30, z - 2, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 3, y + 30, z + 2, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 3, y + 30, z + 3, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 3, y + 30, z + 4, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 3, y + 31, z - 1, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 3, y + 31, z + 0, SABlockList.GreenMushroomBlock, 3, 3);
		world.setBlock(x - 3, y + 31, z + 1, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 2, y + 17, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 2, y + 17, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 2, y + 18, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 2, y + 18, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 2, y + 19, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 2, y + 19, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 2, y + 20, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 2, y + 20, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 2, y + 21, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 2, y + 21, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 2, y + 22, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 2, y + 22, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 2, y + 23, z - 10, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 2, y + 23, z + 10, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 2, y + 24, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 2, y + 24, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 2, y + 25, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 2, y + 25, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 2, y + 26, z - 9, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 2, y + 26, z + 9, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 2, y + 27, z - 8, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 2, y + 27, z + 8, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 2, y + 28, z - 7, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 2, y + 28, z + 7, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 2, y + 29, z - 6, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 2, y + 29, z + 6, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 2, y + 30, z - 5, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 2, y + 30, z - 4, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 2, y + 30, z - 3, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 2, y + 30, z + 3, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 2, y + 30, z + 4, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 2, y + 30, z + 5, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 2, y + 31, z - 2, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 2, y + 31, z - 1, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 2, y + 31, z + 0, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 2, y + 31, z + 1, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 2, y + 31, z + 2, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 1, y + 0, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 1, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 2, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 3, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 4, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 5, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 6, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 7, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 8, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 9, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 10, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 11, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 12, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 13, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 14, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 15, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 16, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 17, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 1, y + 17, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 17, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 1, y + 18, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 1, y + 18, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 18, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 1, y + 19, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 1, y + 19, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 19, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 1, y + 20, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 1, y + 20, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 20, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 1, y + 21, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 1, y + 21, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 21, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 1, y + 22, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 1, y + 22, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 22, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 1, y + 23, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 1, y + 23, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 23, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 1, y + 24, z - 10, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 1, y + 24, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 24, z + 10, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x - 1, y + 25, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 1, y + 25, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 25, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 1, y + 26, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 1, y + 26, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 26, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 1, y + 27, z - 8, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 1, y + 27, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 27, z + 8, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 1, y + 28, z - 7, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 1, y + 28, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 28, z + 7, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 1, y + 29, z - 6, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 1, y + 29, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 29, z + 6, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 1, y + 30, z - 5, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x - 1, y + 30, z - 4, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 1, y + 30, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x - 1, y + 30, z + 4, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 1, y + 30, z + 5, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x - 1, y + 31, z - 3, SABlockList.GreenMushroomBlock, 2, 3);
		world.setBlock(x - 1, y + 31, z - 2, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 1, y + 31, z - 1, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 1, y + 31, z + 0, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 1, y + 31, z + 1, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 1, y + 31, z + 2, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x - 1, y + 31, z + 3, SABlockList.GreenMushroomBlock, 4, 3);
		world.setBlock(x, y + 0, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 0, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 0, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 1, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 1, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 1, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 2, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 2, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 2, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 3, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 3, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 3, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 4, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 4, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 4, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 5, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 5, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 5, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 6, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 6, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 6, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 7, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 7, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 7, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 8, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 8, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 8, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 9, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 9, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 9, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 10, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 10, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 10, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 11, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 11, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 11, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 12, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 12, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 12, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 13, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 13, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 13, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 14, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 14, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 14, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 15, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 15, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 15, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 16, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 16, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 16, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 17, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x, y + 17, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 17, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 17, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 17, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x, y + 18, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x, y + 18, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 18, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 18, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 18, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x, y + 19, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x, y + 19, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 19, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 19, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 19, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x, y + 20, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x, y + 20, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 20, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 20, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 20, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x, y + 21, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x, y + 21, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 21, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 21, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 21, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x, y + 22, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x, y + 22, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 22, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 22, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 22, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x, y + 23, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x, y + 23, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 23, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 23, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 23, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x, y + 24, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x, y + 24, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 24, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 24, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 24, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x, y + 25, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x, y + 25, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 25, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 25, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 25, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x, y + 26, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x, y + 26, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 26, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 26, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 26, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x, y + 27, z - 8, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x, y + 27, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 27, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 27, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 27, z + 8, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x, y + 28, z - 7, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x, y + 28, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 28, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 28, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 28, z + 7, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x, y + 29, z - 6, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x, y + 29, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 29, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 29, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 29, z + 6, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x, y + 30, z - 5, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x, y + 30, z - 4, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x, y + 30, z - 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 30, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 30, z + 1, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x, y + 30, z + 4, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x, y + 30, z + 5, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x, y + 31, z - 3, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x, y + 31, z - 2, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x, y + 31, z - 1, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x, y + 31, z + 0, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x, y + 31, z + 1, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x, y + 31, z + 2, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x, y + 31, z + 3, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 1, y + 0, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 1, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 2, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 3, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 4, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 5, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 6, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 7, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 8, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 9, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 10, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 11, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 12, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 13, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 14, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 15, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 16, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 17, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 1, y + 17, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 17, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 1, y + 18, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 1, y + 18, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 18, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 1, y + 19, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 1, y + 19, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 19, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 1, y + 20, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 1, y + 20, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 20, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 1, y + 21, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 1, y + 21, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 21, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 1, y + 22, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 1, y + 22, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 22, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 1, y + 23, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 1, y + 23, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 23, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 1, y + 24, z - 10, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 1, y + 24, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 24, z + 10, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 1, y + 25, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 1, y + 25, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 25, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 1, y + 26, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 1, y + 26, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 26, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 1, y + 27, z - 8, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 1, y + 27, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 27, z + 8, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 1, y + 28, z - 7, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 1, y + 28, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 28, z + 7, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 1, y + 29, z - 6, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 1, y + 29, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 29, z + 6, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 1, y + 30, z - 5, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 1, y + 30, z - 4, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 1, y + 30, z + 0, SABlockList.GreenMushroomBlock, 10, 3);
		world.setBlock(x + 1, y + 30, z + 4, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 1, y + 30, z + 5, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 1, y + 31, z - 3, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 1, y + 31, z - 2, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 1, y + 31, z - 1, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 1, y + 31, z + 0, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 1, y + 31, z + 1, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 1, y + 31, z + 2, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 1, y + 31, z + 3, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 2, y + 17, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 2, y + 17, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 2, y + 18, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 2, y + 18, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 2, y + 19, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 2, y + 19, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 2, y + 20, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 2, y + 20, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 2, y + 21, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 2, y + 21, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 2, y + 22, z - 10, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 2, y + 22, z + 10, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 2, y + 23, z - 10, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 2, y + 23, z + 10, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 2, y + 24, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 2, y + 24, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 2, y + 25, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 2, y + 25, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 2, y + 26, z - 9, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 2, y + 26, z + 9, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 2, y + 27, z - 8, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 2, y + 27, z + 8, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 2, y + 28, z - 7, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 2, y + 28, z + 7, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 2, y + 29, z - 6, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 2, y + 29, z + 6, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 2, y + 30, z - 5, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 2, y + 30, z - 4, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 2, y + 30, z - 3, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 2, y + 30, z + 3, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 2, y + 30, z + 4, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 2, y + 30, z + 5, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 2, y + 31, z - 2, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 2, y + 31, z - 1, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 2, y + 31, z + 0, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 2, y + 31, z + 1, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 2, y + 31, z + 2, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 3, y + 17, z - 10, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 3, y + 17, z + 10, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 3, y + 18, z - 10, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 3, y + 18, z + 10, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 3, y + 19, z - 10, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 3, y + 19, z + 10, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 3, y + 20, z - 10, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 3, y + 20, z + 10, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 3, y + 21, z - 10, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 3, y + 21, z + 10, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 3, y + 22, z - 10, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 3, y + 22, z + 10, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 3, y + 23, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 3, y + 23, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 3, y + 24, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 3, y + 24, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 3, y + 25, z - 9, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 3, y + 25, z + 9, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 3, y + 26, z - 8, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 3, y + 26, z + 8, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 3, y + 27, z - 8, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 3, y + 27, z + 8, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 3, y + 28, z - 7, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 3, y + 28, z + 7, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 3, y + 29, z - 6, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 3, y + 29, z - 5, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 3, y + 29, z + 5, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 3, y + 29, z + 6, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 3, y + 30, z - 4, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 3, y + 30, z - 3, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 3, y + 30, z - 2, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 3, y + 30, z + 2, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 3, y + 30, z + 3, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 3, y + 30, z + 4, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 3, y + 31, z - 1, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 3, y + 31, z + 0, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 3, y + 31, z + 1, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 4, y + 17, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 4, y + 17, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 4, y + 18, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 4, y + 18, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 4, y + 19, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 4, y + 19, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 4, y + 20, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 4, y + 20, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 4, y + 21, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 4, y + 21, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 4, y + 22, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 4, y + 22, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 4, y + 23, z - 9, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 4, y + 23, z + 9, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 4, y + 24, z - 9, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 4, y + 24, z + 9, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 4, y + 25, z - 8, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 4, y + 25, z + 8, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 4, y + 26, z - 8, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 4, y + 26, z + 8, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 4, y + 27, z - 7, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 4, y + 27, z + 7, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 4, y + 28, z - 6, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 4, y + 28, z + 6, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 4, y + 29, z - 5, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 4, y + 29, z - 4, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 4, y + 29, z + 4, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 4, y + 29, z + 5, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 4, y + 30, z - 3, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 4, y + 30, z - 2, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 4, y + 30, z - 1, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 4, y + 30, z + 0, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 4, y + 30, z + 1, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 4, y + 30, z + 2, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 4, y + 30, z + 3, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 5, y + 17, z - 9, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 5, y + 17, z + 9, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 5, y + 18, z - 9, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 5, y + 18, z + 9, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 5, y + 19, z - 9, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 5, y + 19, z + 9, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 5, y + 20, z - 9, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 5, y + 20, z + 9, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 5, y + 21, z - 9, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 5, y + 21, z + 9, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 5, y + 22, z - 9, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 5, y + 22, z + 9, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 5, y + 23, z - 9, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 5, y + 23, z + 9, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 5, y + 24, z - 8, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 5, y + 24, z + 8, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 5, y + 25, z - 8, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 5, y + 25, z + 8, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 5, y + 26, z - 7, SABlockList.GreenMushroomBlock, 1, 3);
		world.setBlock(x + 5, y + 26, z + 7, SABlockList.GreenMushroomBlock, 5, 3);
		world.setBlock(x + 5, y + 27, z - 7, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 5, y + 27, z + 7, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 5, y + 28, z - 6, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 5, y + 28, z - 5, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 5, y + 28, z + 5, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 5, y + 28, z + 6, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 5, y + 29, z - 4, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 5, y + 29, z - 3, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 5, y + 29, z + 3, SABlockList.GreenMushroomBlock, 9, 3);
		world.setBlock(x + 5, y + 29, z + 4, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 5, y + 30, z - 2, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 5, y + 30, z - 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 5, y + 30, z + 0, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 5, y + 30, z + 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 5, y + 30, z + 2, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 6, y + 17, z - 8, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 6, y + 17, z + 8, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 6, y + 18, z - 8, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 6, y + 18, z + 8, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 6, y + 19, z - 8, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 6, y + 19, z + 8, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 6, y + 20, z - 8, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 6, y + 20, z + 8, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 6, y + 21, z - 8, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 6, y + 21, z + 8, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 6, y + 22, z - 8, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 6, y + 22, z + 8, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 6, y + 23, z - 8, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 6, y + 23, z + 8, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 6, y + 24, z - 8, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 6, y + 24, z + 8, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 6, y + 25, z - 7, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 6, y + 25, z + 7, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 6, y + 26, z - 7, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 6, y + 26, z + 7, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 6, y + 27, z - 6, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 6, y + 27, z + 6, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 6, y + 28, z - 5, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 6, y + 28, z - 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 6, y + 28, z + 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 6, y + 28, z + 5, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 6, y + 29, z - 3, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 6, y + 29, z - 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 6, y + 29, z - 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 6, y + 29, z + 0, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 6, y + 29, z + 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 6, y + 29, z + 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 6, y + 29, z + 3, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 7, y + 17, z - 7, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 7, y + 17, z + 7, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 7, y + 18, z - 7, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 7, y + 18, z + 7, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 7, y + 19, z - 7, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 7, y + 19, z + 7, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 7, y + 20, z - 7, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 7, y + 20, z + 7, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 7, y + 21, z - 7, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 7, y + 21, z + 7, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 7, y + 22, z - 7, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 7, y + 22, z + 7, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 7, y + 23, z - 7, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 7, y + 23, z + 7, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 7, y + 24, z - 7, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 7, y + 24, z + 7, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 7, y + 25, z - 6, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 7, y + 25, z + 6, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 7, y + 26, z - 6, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 7, y + 26, z - 5, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 7, y + 26, z + 5, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 7, y + 26, z + 6, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 7, y + 27, z - 5, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 7, y + 27, z - 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 7, y + 27, z + 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 7, y + 27, z + 5, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 7, y + 28, z - 3, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 7, y + 28, z - 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 7, y + 28, z - 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 7, y + 28, z + 0, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 7, y + 28, z + 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 7, y + 28, z + 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 7, y + 28, z + 3, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 8, y + 17, z - 6, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 8, y + 17, z + 6, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 8, y + 18, z - 6, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 8, y + 18, z + 6, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 8, y + 19, z - 6, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 8, y + 19, z + 6, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 8, y + 20, z - 6, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 8, y + 20, z + 6, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 8, y + 21, z - 6, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 8, y + 21, z + 6, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 8, y + 22, z - 6, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 8, y + 22, z + 6, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 8, y + 23, z - 6, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 8, y + 23, z + 6, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 8, y + 24, z - 6, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 8, y + 24, z - 5, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 8, y + 24, z + 5, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 8, y + 24, z + 6, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 8, y + 25, z - 5, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 8, y + 25, z - 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 8, y + 25, z + 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 8, y + 25, z + 5, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 8, y + 26, z - 4, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 8, y + 26, z - 3, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 8, y + 26, z + 3, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 8, y + 26, z + 4, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 8, y + 27, z - 3, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 8, y + 27, z - 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 8, y + 27, z - 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 8, y + 27, z + 0, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 8, y + 27, z + 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 8, y + 27, z + 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 8, y + 27, z + 3, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 9, y + 17, z - 5, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 9, y + 17, z - 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 17, z + 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 17, z + 5, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 9, y + 18, z - 5, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 9, y + 18, z - 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 18, z + 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 18, z + 5, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 9, y + 19, z - 5, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 9, y + 19, z - 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 19, z + 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 19, z + 5, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 9, y + 20, z - 5, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 9, y + 20, z - 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 20, z + 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 20, z + 5, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 9, y + 21, z - 5, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 9, y + 21, z - 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 21, z + 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 21, z + 5, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 9, y + 22, z - 5, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 9, y + 22, z - 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 22, z + 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 22, z + 5, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 9, y + 23, z - 5, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 9, y + 23, z - 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 23, z - 3, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 23, z + 3, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 23, z + 4, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 23, z + 5, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 9, y + 24, z - 4, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 9, y + 24, z - 3, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 24, z - 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 24, z + 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 24, z + 3, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 24, z + 4, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 9, y + 25, z - 3, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 9, y + 25, z - 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 25, z - 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 25, z + 0, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 25, z + 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 25, z + 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 25, z + 3, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 9, y + 26, z - 2, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 9, y + 26, z - 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 26, z + 0, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 26, z + 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 9, y + 26, z + 2, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 10, y + 17, z - 3, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 10, y + 17, z - 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 17, z - 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 17, z + 0, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 17, z + 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 17, z + 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 17, z + 3, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 10, y + 18, z - 3, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 10, y + 18, z - 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 18, z - 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 18, z + 0, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 18, z + 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 18, z + 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 18, z + 3, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 10, y + 19, z - 3, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 10, y + 19, z - 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 19, z - 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 19, z + 0, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 19, z + 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 19, z + 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 19, z + 3, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 10, y + 20, z - 3, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 10, y + 20, z - 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 20, z - 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 20, z + 0, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 20, z + 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 20, z + 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 20, z + 3, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 10, y + 21, z - 3, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 10, y + 21, z - 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 21, z - 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 21, z + 0, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 21, z + 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 21, z + 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 21, z + 3, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 10, y + 22, z - 3, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 10, y + 22, z - 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 22, z - 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 22, z + 0, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 22, z + 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 22, z + 2, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 22, z + 3, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 10, y + 23, z - 2, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 10, y + 23, z - 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 23, z + 0, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 23, z + 1, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 23, z + 2, SABlockList.GreenMushroomBlock, 6, 3);
		world.setBlock(x + 10, y + 24, z - 1, SABlockList.GreenMushroomBlock, 8, 3);
		world.setBlock(x + 10, y + 24, z + 0, SABlockList.GreenMushroomBlock, 7, 3);
		world.setBlock(x + 10, y + 24, z + 1, SABlockList.GreenMushroomBlock, 6, 3);

		return true;
	}
}